### ISSUE TITLE
from utils import save_image

### ISSUE THREAD

**Issue by GaoTianWL** [Srameo/DNF#10] opened 2023-08-18 06:57 UTC
ImportError: cannot import name 'save_image' from 'utils'

**Comment by Srameo** [comment] 2023-08-19 04:26
The bug was caused by our negligence during development, which has been fixed in commit https://github.com/Srameo/DNF/commit/cd99fa321f2d181882988ab466cda32e28a569ba.

**Closed as completed by Srameo** 2023-08-19 04:26 UTC
Labels: bug
